### ISSUE TITLE
sudo texhash needed?

### ISSUE THREAD

**Issue by AlexanderWillner** [jlelong/chklref#1]
Version: f427396 / MacTex 2015 / OS X 10.11.3

Steps that will reproduce the problem?
1. Follow the installation instructions
2. Invoke chklref -p filename

What is the expected result?
Results.

What happens instead?
`! LaTeX Error: File `chklref.sty' not found.`

Possible workaround:
`sudo texhash`

Any additional information:
Further, I think the config path should be `./configure --with-texmf-prefix=/usr/local/texlive/2015/texmf-local`

**Comment by jlelong** [comment]
Of course, installing new stuff into the TeX tree requires to run `sudo texhash` as noted in the README. I will highlight this point.

Concerning the choice of the texmf prefix. the [TexLive 2015 guide](http://tug.org/texlive/doc/texlive-en/texlive-en.html#x1-100002.2) suggests to use `texlive_root_directory/texmf-local` to store elements to be retained from release to release. In our case, this translates into `/usr/local/texlive/texmf-local`.  It may be possible to use `/usr/local/texlive/2015/texmf-local`, but it looks less standard to me.
