### ISSUE TITLE
./configure is not an internal or external command, nor is it an executable program or batch files.

### ISSUE THREAD

**Issue by haitaoyu0703** [jlelong/chklref#3]
1. Git Bash and Strawberry Perl are installed.
2. CTEX, MikTex and Tex live are installed.
3. My OS is win 10 64bit
4. I don't know how to enter the command line, there are many command lines, e.g. that of win 10 system, Ctex command line, Perl command line. I don't know which command line I should use. Besides, they all shows 
./configure is not an internal or external command, nor is it an executable program or batch files. They can be seen in the below attachments.
Thanks.

![2](https://user-images.githubusercontent.com/57026159/67614196-58c21380-f7eb-11e9-84f2-3838bedc54dd.png)
![1](https://user-images.githubusercontent.com/57026159/67614200-5eb7f480-f7eb-11e9-88c6-8f4a2da63afa.png)
![3](https://user-images.githubusercontent.com/57026159/67614202-65466c00-f7eb-11e9-80d0-5133a8ac88a2.png)
![4](https://user-images.githubusercontent.com/57026159/67614203-66779900-f7eb-11e9-8570-648227409bbb.png)

**Comment by jlelong** [comment]
This was designed to work under Linux. I am currently refactoring most of it to rely only on Perl.
I should be able to get back to you tomorrow with a new release candidate.

**Comment by jlelong** [comment]
Can you try [release 3.0.0](https://github.com/jlelong/chklref/releases/tag/v3.0.0)?
The installation procedure is  completely new, so please read the [README file](https://github.com/jlelong/chklref/blob/master/README.md). 
When it works I will push a new version to CTAN.

**Comment by haitaoyu0703** [comment]
> This was designed to work under Linux. I am currently refactoring most of it to rely only on Perl.
> I should be able to get back to you tomorrow with a new release candidate.

Thanks very much for your update.

**Comment by haitaoyu0703** [comment]
> Can you try [release 3.0.0](https://github.com/jlelong/chklref/releases/tag/v3.0.0)?
> The installation procedure is completely new, so please read the [README file](https://github.com/jlelong/chklref/blob/master/README.md).
> When it works I will push a new version to CTAN.

I am trying through your instructions. Thank you. I will report the result after finishing my tex processing.

**Comment by haitaoyu0703** [comment]
Thanks for your quick response and update. 
I found chklref works well while using it by Local installation mode. It deletes all equation numbers of equations added * in latex file. 

But it shows below pic when using System wide installation mode.
![image](https://user-images.githubusercontent.com/57026159/67658256-08d28080-f994-11e9-9487-bb185525860f.png)

**Comment by jlelong** [comment]
Good to hear!
I do not understand the issue with the system wide approach: `texhash` is just a LaTeX utility to update the database of all available packages. What does happen when calling `chklref.pl` afterwards?

**Comment by haitaoyu0703** [comment]
For the taxhash, I don't know  and maybe the system think they are already included in the environment. For the chkref.pl, it works very well. The screenshot is attached below.
![image](https://user-images.githubusercontent.com/57026159/67666975-dc286400-f9a7-11e9-9fe2-dd71de0c39f1.png)

**Comment by jlelong** [comment]
Great! I will publish it to CTAN.

**Comment by haitaoyu0703** [comment]
> Great! I will publish it to CTAN.

Thanks and Congratulations!
